#!/usr/bin/env python3
# pyright: reportMissingImports=false, reportMissingModuleSource=false
"""Plot reduction-product profiling outputs generated by GGML_REDUCTION_PROD_PROFILE.

Expected input files (same prefix):
- <prefix>_global_hist.csv
- <prefix>_samples.csv
"""

import argparse
import csv
import os
from typing import List, Tuple

import matplotlib.pyplot as plt
import numpy as np


def read_global_hist(path: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    bins: List[int] = []
    lo: List[float] = []
    hi: List[float] = []
    cnt: List[int] = []

    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            bins.append(int(row["bin"]))
            lo.append(float(row["log2_lo"]))
            hi.append(float(row["log2_hi"]))
            cnt.append(int(row["count"]))

    return np.array(bins), np.array(lo), np.array(hi), np.array(cnt)


def read_samples(path: str) -> dict:
    out = {
        "reduction_id": [],
        "n": [],
        "sum": [],
        "sum_abs": [],
        "sum_sq": [],
        "max_abs": [],
        "cancel_ratio": [],
        "neff": [],
        "neff_ratio": [],
        "frac_lt_2p_8": [],
        "frac_lt_2p_10": [],
        "frac_lt_2p_12": [],
    }

    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            for k in out:
                if k in ("reduction_id", "n"):
                    out[k].append(int(row[k]))
                else:
                    out[k].append(float(row[k]))

    for k in out:
        out[k] = np.array(out[k])
    return out


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def plot_global_hist(lo: np.ndarray, hi: np.ndarray, cnt: np.ndarray, out_dir: str) -> None:
    centers = 0.5 * (lo + hi)
    widths = np.maximum(hi - lo, 1e-9)

    plt.figure(figsize=(10, 5))
    plt.bar(centers, cnt, width=widths, align="center", alpha=0.85, edgecolor="black", linewidth=0.3)
    plt.yscale("log")
    plt.xlabel("log2(|x*y|)")
    plt.ylabel("Count (log scale)")
    plt.title("Global Product-Magnitude Histogram")
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "global_hist.png"), dpi=180)
    plt.close()


def plot_cancel_neff(samples: dict, out_dir: str) -> None:
    if samples["n"].size == 0:
        return

    x = samples["cancel_ratio"]
    y = samples["neff_ratio"]
    c = samples["n"]

    plt.figure(figsize=(7, 6))
    sc = plt.scatter(x, y, c=c, cmap="viridis", s=9, alpha=0.7)
    plt.xlabel("Cancellation ratio |sum(p)| / sum(|p|)")
    plt.ylabel("Effective terms ratio neff / n")
    plt.title("Reduction Stability Map")
    cb = plt.colorbar(sc)
    cb.set_label("n (reduction length)")
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "cancel_vs_neff_ratio.png"), dpi=180)
    plt.close()


def plot_small_frac(samples: dict, out_dir: str) -> None:
    if samples["n"].size == 0:
        return

    plt.figure(figsize=(10, 5))
    bins = np.linspace(0.0, 1.0, 41)
    plt.hist(samples["frac_lt_2p_8"], bins=bins, alpha=0.55, label="frac < 2^-8 * max|p|", density=True)
    plt.hist(samples["frac_lt_2p_10"], bins=bins, alpha=0.55, label="frac < 2^-10 * max|p|", density=True)
    plt.hist(samples["frac_lt_2p_12"], bins=bins, alpha=0.55, label="frac < 2^-12 * max|p|", density=True)
    plt.xlabel("Fraction in one reduction")
    plt.ylabel("Density")
    plt.title("Small-Product Fraction Distribution")
    plt.legend()
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "small_fraction_hist.png"), dpi=180)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot reduction-product profiler outputs")
    parser.add_argument(
        "--prefix",
        default="./reduction_prod_profile",
        help="Prefix used by GGML_REDUCTION_PROD_PROFILE_PREFIX (default: ./reduction_prod_profile)",
    )
    parser.add_argument(
        "--out-dir",
        default="./reduction_prod_plots",
        help="Directory for output figures",
    )
    args = parser.parse_args()

    hist_csv = f"{args.prefix}_global_hist.csv"
    samples_csv = f"{args.prefix}_samples.csv"

    if not os.path.exists(hist_csv):
        raise FileNotFoundError(f"Missing file: {hist_csv}")
    if not os.path.exists(samples_csv):
        raise FileNotFoundError(f"Missing file: {samples_csv}")

    ensure_dir(args.out_dir)

    _, lo, hi, cnt = read_global_hist(hist_csv)
    samples = read_samples(samples_csv)

    plot_global_hist(lo, hi, cnt, args.out_dir)
    plot_cancel_neff(samples, args.out_dir)
    plot_small_frac(samples, args.out_dir)

    print("Saved figures:")
    print(f"- {os.path.join(args.out_dir, 'global_hist.png')}")
    print(f"- {os.path.join(args.out_dir, 'cancel_vs_neff_ratio.png')}")
    print(f"- {os.path.join(args.out_dir, 'small_fraction_hist.png')}")


if __name__ == "__main__":
    main()
